
server:
  port: 8088
  host: 0.0.0.0

db:
  source: jdbc
  connection:
    url: jdbc:postgresql://localhost:5432/helidontest
    username: postgres
    password: admin
    poolName: hikariPool
  services:
    metrics:
      - type: METER
  health-check:
    type: "dml"
    statementName: "ping"
  statements:
    # Ping statement
    ping: "SET @HELIDON_PING=0"